# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('genre', models.CharField(default='Action RPG', max_length=100)),
                ('engine', models.CharField(choices=[('UNREAL_5', 'Unreal Engine 5'), ('UNITY_6', 'Unity 6'), ('GODOT_4', 'Godot Engine 4'), ('CUSTOM_CPP', 'Custom Proprietary C++'), ('CRYENGINE', 'CryEngine')], default='UNREAL_5', max_length=40)),
                ('platforms', models.CharField(default='PC, PlayStation 5, Xbox Series X', max_length=255)),
                ('status', models.CharField(choices=[('PLANNING', 'Planning & Concept'), ('PRE_PRODUCTION', 'Pre-Production'), ('PRODUCTION', 'Full Production'), ('TESTING', 'QA & Playtesting'), ('BETA', 'Closed / Open Beta'), ('RELEASED', 'Released / Live'), ('MAINTENANCE', 'LiveOps & Maintenance'), ('ARCHIVED', 'Archived')], default='PRODUCTION', max_length=30)),
                ('summary', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='game_covers/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='game_banners/')),
                ('target_release_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=500000.0, max_digits=12)),
                ('repository_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_games', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='organizations.organization')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='GameMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('due_date', models.DateField()),
                ('is_completed', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='games.game')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
