# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.CharField(choices=[('STEAM', 'Steam'), ('EPIC_GAMES', 'Epic Games Store'), ('PLAYSTATION_STORE', 'PlayStation Store'), ('XBOX_STORE', 'Xbox Store'), ('NINTENDO_ESHOP', 'Nintendo eShop'), ('GOG', 'GOG.com'), ('APPLE_APP_STORE', 'Apple App Store'), ('GOOGLE_PLAY', 'Google Play Store')], default='STEAM', max_length=40)),
                ('headline', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=350)),
                ('full_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, default=59.99, max_digits=7)),
                ('discount_percentage', models.PositiveIntegerField(default=0)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('UNDER_REVIEW', 'Store Review'), ('APPROVED', 'Approved by Platform'), ('PUBLISHED', 'Published / Live'), ('HIDDEN', 'Hidden')], default='PUBLISHED', max_length=30)),
                ('store_url', models.URLField(blank=True)),
                ('tags', models.CharField(default='Action, RPG, Open World, Co-op, Souls-like', max_length=255)),
                ('min_cpu', models.CharField(default='Intel Core i5-8400 or AMD Ryzen 5 2600', max_length=150)),
                ('min_gpu', models.CharField(default='NVIDIA GeForce GTX 1060 6GB or AMD Radeon RX 580', max_length=150)),
                ('min_ram_gb', models.PositiveIntegerField(default=16)),
                ('min_storage_gb', models.PositiveIntegerField(default=75)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_listings', to='games.game')),
            ],
            options={
                'ordering': ['game', 'store'],
                'unique_together': {('game', 'store')},
            },
        ),
    ]
