# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_number', models.PositiveIntegerField()),
                ('platform', models.CharField(choices=[('WINDOWS_X64', 'Windows (x64)'), ('LINUX_X64', 'Linux (x86_64)'), ('MACOS_ARM64', 'macOS (Apple Silicon)'), ('PS5', 'PlayStation 5'), ('XBOX_SERIES', 'Xbox Series X/S'), ('NINTENDO_SWITCH', 'Nintendo Switch'), ('ANDROID_APK', 'Android (AAB / APK)'), ('IOS_IPA', 'iOS (IPA)')], default='WINDOWS_X64', max_length=40)),
                ('status', models.CharField(choices=[('PENDING', 'Pending in CI Queue'), ('BUILDING', 'Compiling / Cooking'), ('SUCCESSFUL', 'Build Successful'), ('FAILED', 'Build Failed / Cook Error'), ('TESTING', 'In Smoke Testing'), ('APPROVED', 'QA Approved for Release'), ('REJECTED', 'QA Rejected')], default='SUCCESSFUL', max_length=30)),
                ('git_commit_hash', models.CharField(default='e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855', max_length=64)),
                ('branch_name', models.CharField(default='main', max_length=100)),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=1420.0, max_digits=8)),
                ('qa_notes', models.TextField(blank=True)),
                ('build_duration_sec', models.PositiveIntegerField(default=480)),
                ('build_date', models.DateTimeField(auto_now_add=True)),
                ('developer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_builds', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='games.game')),
                ('qa_tester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_builds', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='builds', to='versions.gameversion')),
            ],
            options={
                'ordering': ['-build_date'],
                'unique_together': {('game', 'build_number')},
            },
        ),
    ]
