# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.CharField(help_text='e.g. v1.2.0', max_length=50)),
                ('release_type', models.CharField(choices=[('ALPHA', 'Alpha Prototype'), ('BETA', 'Beta Preview'), ('RC', 'Release Candidate'), ('MAJOR', 'Major Milestone (v1.0, v2.0)'), ('MINOR', 'Feature Update'), ('PATCH', 'Patch / Hotfix')], default='MINOR', max_length=30)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active Development'), ('RELEASED', 'Released'), ('DEPRECATED', 'Deprecated')], default='ACTIVE', max_length=30)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('changelog', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='games.game')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('game', 'version_number')},
            },
        ),
    ]
