# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
        ('games', '0001_initial'),
        ('versions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_code', models.CharField(max_length=60, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('target_platform', models.CharField(default='Steam, PS5, Xbox Series X', max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('PREPARING', 'Preparing Staging'), ('QA', 'In Final QA Verification'), ('APPROVED', 'Approved for Deployment'), ('PUBLISHED', 'Published / Live'), ('ROLLED_BACK', 'Rolled Back')], default='PLANNED', max_length=30)),
                ('scheduled_date', models.DateTimeField()),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('release_notes', models.TextField(blank=True)),
                ('deployment_logs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_releases', to=settings.AUTH_USER_MODEL)),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='builds.build')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_releases', to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='games.game')),
                ('version', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='versions.gameversion')),
            ],
            options={
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='ReleaseChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(max_length=250)),
                ('is_completed', models.BooleanField(default=False)),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='releases.release')),
            ],
        ),
    ]
