# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('3D_MODEL', '3D Model / Mesh'), ('TEXTURE', 'Texture / Material (PBR)'), ('AUDIO', 'SFX / Sound Effect'), ('MUSIC', 'Music / Soundtrack'), ('UI', 'UI / Iconography'), ('VFX', 'VFX / Particle / Shader'), ('ANIMATION', 'Skeletal Animation'), ('CONCEPT', 'Concept Art / Storyboard'), ('DOC', 'Design Doc / Script')], default='3D_MODEL', max_length=30)),
                ('file', models.FileField(blank=True, null=True, upload_to='assets/')),
                ('file_size_mb', models.DecimalField(decimal_places=2, default=12.5, max_digits=8)),
                ('format_extension', models.CharField(default='.fbx', max_length=20)),
                ('version', models.CharField(default='v1.0', max_length=30)),
                ('poly_count', models.PositiveIntegerField(blank=True, help_text='For 3D Models', null=True)),
                ('resolution', models.CharField(blank=True, help_text='e.g. 4096x4096', max_length=50)),
                ('audio_duration_sec', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='games.game')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_assets', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='projects.project')),
                ('tags', models.ManyToManyField(blank=True, to='assets.assettag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
