# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InGameItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('sku', models.CharField(max_length=80, unique=True)),
                ('item_type', models.CharField(choices=[('COSMETIC_SKIN', 'Hero / Weapon Skin'), ('BATTLE_PASS', 'Seasonal Battle Pass'), ('CURRENCY_PACK', 'Virtual Gems / Gold Pack'), ('DLC_EXPANSION', 'Expansion Story Pack'), ('CONSUMABLE', 'XP Boost / Consumable')], default='COSMETIC_SKIN', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, default=9.99, max_digits=8)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_items', to='games.game')),
            ],
            options={
                'ordering': ['game', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('REFUNDED', 'Refunded'), ('FAILED', 'Failed / Declined')], default='COMPLETED', max_length=20)),
                ('payment_gateway', models.CharField(choices=[('STEAM_WALLET', 'Steam Microtransactions'), ('STRIPE', 'Stripe Direct'), ('PSN', 'PlayStation Network'), ('XBOX_LIVE', 'Xbox Live Marketplace')], default='STEAM_WALLET', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='games.game')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='monetization.ingameitem')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='players.player')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
