# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('metric_type', models.CharField(choices=[('HIGH_SCORE', 'High Score (Points)'), ('FASTEST_TIME', 'Speedrun / Time (Milliseconds)'), ('KILL_COUNT', 'Eliminations / Kills'), ('LEVEL_REACHED', 'Highest Wave / Level'), ('WIN_STREAK', 'Consecutive Win Streak')], default='HIGH_SCORE', max_length=30)),
                ('sort_order', models.CharField(choices=[('DESC', 'Descending (Higher is better)'), ('ASC', 'Ascending (Lower is better e.g. Speedrun)')], default='DESC', max_length=10)),
                ('season_name', models.CharField(default='Season 1: Genesis', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='games.game')),
            ],
            options={
                'ordering': ['game', 'name'],
                'unique_together': {('game', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.BigIntegerField()),
                ('formatted_score', models.CharField(default='10,000 pts', max_length=50)),
                ('rank', models.PositiveIntegerField(default=1)),
                ('achieved_at', models.DateTimeField(auto_now=True)),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='leaderboards.leaderboard')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_scores', to='players.player')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('leaderboard', 'player')},
            },
        ),
    ]
