# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_data_json', models.TextField(blank=True, default='{}')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_events', to='games.game')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='players.player')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_date', models.DateField()),
                ('dau', models.PositiveIntegerField(default=12500, help_text='Daily Active Users')),
                ('mau', models.PositiveIntegerField(default=85000, help_text='Monthly Active Users')),
                ('avg_fps', models.DecimalField(decimal_places=1, default=59.4, max_digits=5)),
                ('crash_count', models.PositiveIntegerField(default=12)),
                ('revenue_usd', models.DecimalField(decimal_places=2, default=14500.0, max_digits=12)),
                ('new_installs', models.PositiveIntegerField(default=3400)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_metrics', to='games.game')),
            ],
            options={
                'ordering': ['-metric_date'],
                'unique_together': {('game', 'metric_date')},
            },
        ),
    ]
