# Generated by Django 5.0.6 on 2026-09-04 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('STUDIO_EXECUTIVE', 'Executive Studio Summary'), ('QA_DEFECT_VELOCITY', 'QA Bug & Triage Velocity'), ('REVENUE_AND_COMMERCE', 'Monetization & Sales Breakdown'), ('DEVELOPMENT_BURNDOWN', 'Task & Sprint Velocity'), ('PLAYER_ENGAGEMENT', 'Player Engagement & DAU')], default='STUDIO_EXECUTIVE', max_length=40)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
