# Generated by Django 5.0.6 on 2026-09-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ORG_ADMIN', 'Organization Admin'), ('PROJECT_MANAGER', 'Project Manager'), ('LEAD_DEVELOPER', 'Lead Developer'), ('DEVELOPER', 'Developer'), ('DESIGNER', 'Designer / Artist'), ('QA_TESTER', 'QA Tester'), ('MARKETING_MANAGER', 'Marketing Manager'), ('SUPPORT_AGENT', 'Support Agent'), ('VIEWER', 'Viewer / Stakeholder')], max_length=30)),
                ('module_name', models.CharField(max_length=50)),
                ('can_view', models.BooleanField(default=True)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve_release', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['role', 'module_name'],
                'unique_together': {('role', 'module_name')},
            },
        ),
    ]
